version: '3.8'

services:
  browsing-jobs:
    build: ./browsing-jobs
    ports:
      - "8497:80"
    depends_on:
      - backend

  hr-side-posting:
    build:
      context: ./hr-side posting
    ports:
      - "8498:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "3321:3321"
    environment:
      - PORT=3321
      - DB_USER=postgres
      - DB_PASSWORD=admin321
      - DB_NAME=job_portal_db
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5981:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin321
      POSTGRES_DB: job_portal_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

